### ISSUE TITLE
调整配置文件格式

### ISSUE THREAD

**Issue by SoraKasvgano** [lanthora/candy#340]
1.conf有无必要切成yaml或toml，趁着用户还不是很多的时候

2.客户端配置文件里有无必要为每个客户端单独配置一个别名，比如某台电脑的名字，这样在查看server端日志的时候可以很方便定位出问题的机器。(若无配置则由客户端随机生成一个名字)
比如 [2024-04-26 02:42:01.893] [info] connect: [m3600c]10.10.10.132,
[2024-04-26 02:42:29.473] [info] connect: [hpnuc]10.10.10.133,
[2024-04-26 02:42:50.291] [info] connect: [dell-desktop]10.10.10.134,
[2024-04-26 02:43:04.745] [info] disconnect: [macbook]10.10.10.126

**Comment by lanthora** [comment]
> 1.conf有无必要切成yaml或toml，趁着用户还不是很多的时候

最近在考虑这个问题,不过得保持兼容性,可能可以根据配置文件的后缀名区分.

> 2.客户端配置文件里有无必要为每个客户端单独配置一个别名，比如某台电脑的名字，这样在查看server端日志的时候可以很方便定位出问题的机器。(若无配置则由客户端随机生成一个名字)

这个可以,感觉可以直接用配置里写的 `name`,如果用 toml 格式的话,就可以用 `section` 的名称替换掉 `name`,然后允许一个客户端同时加入多个网络

**Comment by lanthora** [comment]
@SoraKasvgano 认为这个功能有必要的话可以发 PR, 暂时我不计划在这方面投入精力

**Comment by lanthora** [comment]
@SoraKasvgano 看上去你用的服务端分配的 IP,如果是自己的设备,为什么不直接指定静态 IP 呢
