### ISSUE TITLE
discovery = 0是不是意味着断网不会立刻重连，网络不好的可以开启

### ISSUE THREAD

**Issue by aogg** [lanthora/candy#360]
discovery = 0是不是意味着断网不会立刻重连，网络不好的可以开启

**Comment by lanthora** [comment]
> discovery = 0是不是意味着断网不会立刻重连，网络不好的可以开启

断网分不同情况，以最极端的拔网线为例，客户端在 30 秒内没有收到服务端的任何消息将会重连，重连策略与这个值无关。

这个项目的实现在默认情况下不会主动与其他客户端建立 P2P 连接，只有在两个客户端产生通信流量是才会开始建连，对应的现象就是 ping 的前几个包延迟会高一些。

后来添加了客户端中继功能，基于上面的策略，中继节点需要尽可能的与其他客户端先建立 P2P 连接。

这个值的含义是"每间隔 x 秒向网络中广播，让其他客户端主动与自己建立 P2P 连接"

所以配置为 0 表示只会与主动连接过的设备建立 P2P，否则每隔 x 秒尝试与其他设备建立直连，由于广播消耗的流量比较多，建议保持默认配置

**Comment by aogg** [comment]
所以连接过了，拔网线，判断断开，过会插上去，

如果此时discovery = 0，就不会再连接之前连接过的，需要等下一次有对等网络的请求才连接

如果discovery = 30，就会再断开的30秒后再连接


是吧

如果是就最好了

**Comment by lanthora** [comment]
@aogg 不是, discovery 与重连没有任何关系.无论你怎么配置,都是 30 秒内发现断开,然后触发进程重启

**Comment by aogg** [comment]
加个参数吧，断开重连的时间，否则一直断网在低配置服务器上就会奔溃，之前tinc就是这样的情况

**Comment by aogg** [comment]
那你docker容器加个systemd，还有docker有--restart但这个是没有时间控制的，不能只用一个docker容器解决

**Comment by lanthora** [comment]
@aogg 在 docker 里面放 systemd 是很离谱的事情.不能这么做

现在程序的逻辑是: 1. 能正常运行就正常运行 2. 不能正常运行就退出,断网只是不能正常运行的情况之一

我不计划为 docker 不能设置重启间隔做特殊处理,这是 docker 的问题.你可以尝试下 docker 的其他代替品,我自己是在用 podman, 可以设置重启间隔.

**Comment by aogg** [comment]
--stop-signal |   | Signal to stop the container
-- | -- | --
--stop-timeout |   | API 1.25+ Timeout (in seconds) to stop a container

[--stop-signal](https://docs.docker.com/reference/cli/docker/container/run/#stop-signal)		Signal to stop the container
[--stop-timeout](https://docs.docker.com/reference/cli/docker/container/run/#stop-timeout)		API 1.25+ Timeout (in seconds) to stop a container


这个吗，这两个参数好像是兼容的，你文档加个-d后台运行的吧，为什么文档是--rm

**Comment by lanthora** [comment]
@aogg 从描述上来看 --stop-timeout 不是你想要的东西.

如果重启时间间隔这么重要的话,我计划修改一个现在已有的参数.
现在 --auto-restart 表示自动重启.可以把这个参数改成 --restart x.
x 为 0 或者不配置时表示不重启,否侧重启间隔 x 秒.

--rm 可以让不懂 docker 的人在测试后关闭容器.懂的人知道要怎么改.
