### ISSUE TITLE
双桟环境无法连接服务端

### ISSUE THREAD

**Issue by 13653216371** [lanthora/candy#402]
服务器支持双桟环境
服务器域名解析存在A和AAAA解析
客户端支持双桟环境

问题现象：无任何显示
![image](https://github.com/lanthora/candy/assets/110286972/c6d007a6-c776-456a-aa5a-afdcc7ccacac)

解决办法：PC端网卡关闭IPV6或者服务器域名去掉AAAA解析

这可能需要支持V6才行了，或者只解析V4

**Comment by lanthora** [comment]
@13653216371 删掉 --tun 的配置,让服务器分配地址,然后贴 --debug 日志看看.如果是和服务器之间连接出现问题应该不能成功分配地址.

**Comment by peeweep** [comment]
> 这可能需要支持V6才行了，或者只解析V4

我使用下来是支持 v6 的。

我的服务端是在 Cloudflare CDN 后边，域名有A AAAA 解析。
在双栈机器上用 v4 和 v6 都可以连到服务端，也可以在 hosts 中指定  v6，仅供参考。

**Comment by 13653216371** [comment]
ok
