### ISSUE TITLE
只能支持单线程运行

### ISSUE THREAD

**Issue by ChanningHe** [lanthora/candy#406]
![66fbb0b9d29affd6756e5896be55de44](https://github.com/lanthora/candy/assets/52875777/ace99df8-95f0-4f8f-b127-a21d877ef993)

在Zen2 IPC下3.0GHz的处理器下只能达到200Mbps+的iperf3转发

**Comment by lanthora** [comment]
测试一下 UDP 的情况,我这边测试发现用 `-u -b 1000M` 几乎能够跑满千兆.可能问题出在了 TCP 协议上,由于丢包或者乱序到达导致限制了 TCP 的性能.

在 https://github.com/lanthora/candy/pull/405 里添加了多线程支持,`--worker=x` 开启多线程,x 表示线程数量,默认值为 0 表示不用多线程.我自己的环境测试发现确实会开更多线程,但是性能更差了.可能引入多线程的开销比原本的处理更大.

**Comment by lanthora** [comment]
已经支持 P2P 多个线程处理请求,目前性能瓶颈在发送方,需要支持处理 TUN 消息是多线程加密
