### ISSUE TITLE
服务端是否有考虑包含客户端功能？

### ISSUE THREAD

**Issue by ctermiii** [lanthora/candy#410]
启动服务端生成tun和ip， 这样服务器不需要在运行一个client即可跟另外的client通信

**Comment by lanthora** [comment]
@ctermiii 早期版本是支持在一个进程里同时开客户端和服务端的.但是在后来的版本中[移除](https://github.com/lanthora/candy/commit/2be1a578f73395086181975d5860cb21dfc37d18)了.在服务端中包含客户端唯一的好处是不需要再开一个进程.但是会增加配置的复杂度,而且如果客户端部分的代码出现问题会导致其他所有服务端都断开.最终的决定是在配置上就将他们分开.代价就是要多写一份配置.

**Comment by ctermiii** [comment]
收到，感谢回复。
