### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by ferocknew** [lanthora/candy#411]
1. 命令行下，如何查看服务端接入的客户端？
2. [Cucurbita](https://hub.docker.com/r/lanthora/cucurbita) ，如何管理已有的服务端？

**Comment by lanthora** [comment]
> 1. 命令行下，如何查看服务端接入的客户端？

看日志,目前没有统一的查看接入客户端的方法,你有好的想法可以 PR

> 2. [Cucurbita](https://hub.docker.com/r/lanthora/cucurbita) ，如何管理已有的服务端？

管理服务端? 这只是一个 Web 版本的服务端,没有办法去管理其他服务端

**Comment by ferocknew** [comment]
> > 1. 命令行下，如何查看服务端接入的客户端？
> 
> 看日志,目前没有统一的查看接入客户端的方法,你有好的想法可以 PR
> 
> > 2. [Cucurbita](https://hub.docker.com/r/lanthora/cucurbita) ，如何管理已有的服务端？
> 
> 管理服务端? 这只是一个 Web 版本的服务端,没有办法去管理其他服务端

那，日志在哪儿看呢？日志路径或者命令？
查了一下cfg 文件没有定义日志文件的地方，只有一个debug 的开关

**Comment by ferocknew** [comment]
另，[Cucurbita](https://hub.docker.com/r/lanthora/cucurbita) 这个web 版的服务端，如何被 nginx 反代？
刚刚尝试启动了以后，发现，怎么也没法添加网络设置，点了插入没反应。

**Comment by lanthora** [comment]
> 另，[Cucurbita](https://hub.docker.com/r/lanthora/cucurbita) 这个web 版的服务端，如何被 nginx 反代？ 刚刚尝试启动了以后，发现，怎么也没法添加网络设置，点了插入没反应。

看不懂你的问题,不要在一个 issue 里问太多问题,拆分成独立问题并清楚的描述你已经做了什么操作.
