### ISSUE TITLE
如何查看由 systemctl 启动的进程的日志

### ISSUE THREAD

**Issue by ferocknew** [lanthora/candy#412]
如题，麻烦告知日志查看的方式。

**Comment by lanthora** [comment]
> 如题，麻烦告知日志查看的方式。

日志是打印到标注输出的,你是以什么方式启动的进程.

**Comment by ferocknew** [comment]
根据文档

```bash
apt install --fix-broken ./xxx.deb
systemctl enable --now candy
```

**Comment by lanthora** [comment]
> 根据文档
> 
> ```shell
> apt install --fix-broken ./xxx.deb
> systemctl enable --now candy
> ```

日志由 systemd 管理,简单来说执行这个命令能看到日志

```bash
journalctl -u candy
```

更多细节可以看 systemd 和 journalctl 的文档.

**Comment by ferocknew** [comment]
看到了，谢谢

另外
```txt
7月 10 15:14:01 debian1253 candy[1542078]: [info] listen: 0.0.0.0:xxxx
7月 10 15:22:06 debian1253 candy[1542078]: [info] connect: 172.xx.xx.139
7月 10 15:27:03 debian1253 candy[1542078]: [info] connect: 172.xx.xx.140
```

日志是不是过于简单了？ 客户端的 cfg 配置了name，如果日志里能体现出 name 那可能更好点。
现在有IP，但是，多了不知道 IP 是哪个 客户端。

**Comment by lanthora** [comment]
> 看到了，谢谢
> 
> 另外
> 
> ```
> 7月 10 15:14:01 debian1253 candy[1542078]: [info] listen: 0.0.0.0:xxxx
> 7月 10 15:22:06 debian1253 candy[1542078]: [info] connect: 172.xx.xx.139
> 7月 10 15:27:03 debian1253 candy[1542078]: [info] connect: 172.xx.xx.140
> ```
> 
> 日志是不是过于简单了？ 客户端的 cfg 配置了name，如果日志里能体现出 name 那可能更好点。 现在有IP，但是，多了不知道 IP 是哪个 客户端。

客户端配置的 name 只有一个作用.就是在同一台设备上配置多个客户端的时候避免冲突的,这个值不会上报到服务端.为了保持跟早期版本的兼容性,不能修改登录的报文,因此没有办法在登录时显示出客户端的名字.

在 web 版本的服务端(cucurbita)里解决了这个问题,客户端会在心跳中携带 hostname,能够在网页上看到主机名.
