### ISSUE TITLE
cucurbita 服务端怎么使用？

### ISSUE THREAD

**Issue by ferocknew** [lanthora/candy#413]
如题
1. cucurbita 服务端有ws 端口么？nginx 可以反代，对吧
2. cucurbita 服务端有文档么？求地址

**Comment by ferocknew** [comment]
ok, 明白了，因为是http+ws 服务，所以我才顾虑。
建议，http 和ws 分开，因为 http 提供管理功能，大概率不会对外公开。

**Comment by lanthora** [comment]
> ok, 明白了，因为是http+ws 服务，所以我才顾虑。 建议，http 和ws 分开，因为 http 提供管理功能，大概率不会对外公开。

能够想象如果分开就会多出类似 "明明浏览器能访问,为什么客户独连不上" 的问题.暂时不考虑分开,如果有这么强的安全要求,可以在 nginx 的配置里分成两个端口,只对外网公开 websocket

**Comment by ferocknew** [comment]
`如果有这么强的安全要求,可以在 nginx 的配置里分成两个端口`

怎么做到？
