### ISSUE TITLE
屏蔽客户端某节点的路由

### ISSUE THREAD

**Issue by david88558855** [lanthora/candy#414]
环境：客户端192.168.139.22，内网192.168.31.22， 另一台其他地区的设备192.168.139.11，内网192.168.31.11，，，两个地区都是内网192.168.31.0网段

想让 192.168.31.22 能直接访问真实局域网 192.168.31.99地址, 但是现在因为 （192.168.139.11虚拟ip，内网地址192.168.31.11）的路由导致流量会绕道 （192.168.139.11虚拟ip，内网地址192.168.31.11）这台另一个地区机的器上

**Comment by lanthora** [comment]
提供服务端的网络配置的路由配置和相关客户端的局域网 IP 和在虚拟 IP.

**Comment by lanthora** [comment]
通过细化路由的粒度可以解决,这个问题是由于给非必要的设备下发了非必要的路由导致的.如果能补充更细节的信息可以 reopen
