### ISSUE TITLE
子网代理（点对网）的服务端和客户端如何配置

### ISSUE THREAD

**Issue by jinshuqishi2019** [lanthora/candy#415]
![2024-07-11 17 16 32](https://github.com/lanthora/candy/assets/57516638/a667d8ae-5ecc-4790-bfbe-04a8ab0f89d8)

对于上图的网络情况如何配置。
作者已经实现 [多局域网组网](https://docs.canets.org/sdwan.html)，能力有限不明白教程（网对网）中的操作怎么配置成我需要的点对网。

谢谢热心网友答疑解惑。

**Comment by lanthora** [comment]
节点 B(10.144.144.2) 和 10.1.1.0/24 是什么关系,是这个网络的网关,还是只是这个网络里的一个普通终端设备

**Comment by jinshuqishi2019** [comment]
节点B在candy网络中是10.144.144.2，在10.1.1.0/24（非该网络网关）局域网中是普通终端设备例如：10.1.1.10。

**Comment by lanthora** [comment]
> 节点B在candy网络中是10.144.144.2，在10.1.1.0/24（非该网络网关）局域网中是普通终端设备例如：10.1.1.10。

由于 candy 的实现方式是把原始包直接发过去,在 10.1.1.0/24 的设备上看到的原 IP 是 10.144.144.1,所以得需要让 10.1.1.0/24 的设备上有一条路由是: 发往 10.144.144.1 的包通过 10.144.144.2 转发.也就是对应文档的[这一部分](https://docs.canets.org/sdwan.html#%E6%B5%81%E9%87%8F%E8%BD%AC%E5%8F%91%E5%88%B0%E7%BD%91%E5%85%B3)具体配置方法取决于你的路由器,甚至有些路由器不支持,需要在终端上单独配置.

如果能搞定上面的问题,或者把 10.144.144.2 装到网关上,只需要在服务端加一条 sdwan="10.144.144.1/32,10.1.1.0/24,10.144.144.2"
