### ISSUE TITLE
多服务器组网出口问题

### ISSUE THREAD

**Issue by whoisgit** [lanthora/candy#416]
客户端B 10.0.0.2, 客户端A 10.0.0.1, 网卡名candy-test，目前想通过客户端B访问8.8.8.8这个ip 经过10.0.0.1作为出口
在服务端配置sdwan = "10.0.0.2/32,8.8.8.8/32,10.0.0.1", 10.0.0.1开启了net.ipv4.ip_forward = 1, 然后按照教程做了转发规则：
iptables -t nat -A POSTROUTING -o candy-test -j MASQUERADE
iptables -A FORWARD -i eth0 -o candy-test -j ACCEPT
iptables -A FORWARD -i candy-test -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
=====
最后从客户端B测试ping 目标，发现ping不通，去客户端A抓包也只有请求，没有回复，后来发现iptables FORWARD 一直被drop
请教了群友，让我改了一下iptables变了一下客户端A的-i -o顺序：
iptables -t nat -A POSTROUTING -s 10.0.0.2/32 -o eth0 -j MASQUERADE
iptables -A FORWARD -i candy-test -o eth0 -j ACCEPT
iptables -A FORWARD -i eth0 -o candy-test -m state --state RELATED,ESTABLISHED -j ACCEPT

现在成功把客户端A当作出口。

**Comment by lanthora** [comment]
iptables 规则配置问题,需要接受从 candy-test 发送到 eth0 的报文.对应的 iptables 规则应该修改为

```bash
iptables -A FORWARD -i candy-test -o eth0 -j ACCEPT
iptables -A FORWARD -i eth0 -o candy-test -m state --state RELATED,ESTABLISHED -j ACCEPT
```
