### ISSUE TITLE
Windows GUI 配置文件位置问题

### ISSUE THREAD

**Issue by ljty214** [lanthora/candy#419]
candy的Windows图形客户端cake软件，网络配置好了，找的到对应的网络配置文件吗？还有如何保存已配置好的网络？

**Comment by lanthora** [comment]
> candy的Windows图形客户端cake软件，网络配置好了，找的到对应的网络配置文件吗？还有如何保存已配置好的网络？

图形界面的配置文件在 Windows 上保存在注册表，具体注册表的位置可以看图形界面的代码

**Comment by ljty214** [comment]
虽然没看懂图形界面的代码，但是还是在注册表里找到了已配置好的网络配置。。。。。。
