### ISSUE TITLE
客户端软件设置有问题吗？

### ISSUE THREAD

**Issue by ljty214** [lanthora/candy#421]
本人现在在用的是win7 64位系统，客户端已加入网络，数据包已发送有数据，但已接收的数据包为0，是客户端设置有问题吗？要怎么改设置呢

**Comment by ljty214** [comment]
![22](https://github.com/user-attachments/assets/9acc2b59-3e92-4589-ad1a-5a5d9ae2b247)

**Comment by lanthora** [comment]
补充 Candy 的配置信息,包括服务端和两个客户端的配置文件或命令行参数.

**Comment by lanthora** [comment]
你在实际使用过程中出现了什么不符合预期的现象吗,如果没有出现就是没有问题

**Comment by lanthora** [comment]
我能回答的问题范围是:__根据文档操作后无法达成文档中描述的效果__.如果认为没有达成文档中描述的效果需要给出进行判断的方法.你提供的信息我做不出任何判断.我也不了解 windows, 贴出 windows 上的截图没有价值.

**Comment by lanthora** [comment]
> "但已接收的数据包为0"

有任何其他客户端向这台机器发包了吗? 

如果你认为发包了,你是如何判断发包了的? 比如你亲自在其他设备上发送了 ping 包?
