### ISSUE TITLE
Linux 如何同时加入多个网络

### ISSUE THREAD

**Issue by ljty214** [lanthora/candy#423]
有时某台主机有需要同时连两个不同的candy网络，cake软件是没问题的。请问Linux主机或win7系统如何同时两个不同的candy网络，该怎么操作设置呢？

**Comment by lanthora** [comment]
@ljty214 每各 issue 只解决一个问题,你准备在这个里面解决 linux 还是 win7

**Comment by ljty214** [comment]
linux系统

**Comment by lanthora** [comment]
@ljty214 具体是怎么安装的，不同的安装方法操作步骤不同

**Comment by ljty214** [comment]
比如Ubuntu系统，就按照说明的方式安装的

**Comment by lanthora** [comment]
@ljty214 对于用发行版安装包方式安装的来说，只需要把配置文件放到 /etc/candy.d/xxx.cfg， 然后用 systemctl enable --now candy@xxx 启动就可以，xxx 是文件名，可以随意替换，同时要注意多个配置文件中的 name 要不同

**Comment by ljty214** [comment]
比如分别加入2个不同的网关A和B,分别对应配置文件candyA.cfg，candyB.cfg，然后就是启动命令systemctl enable --now candy@candyA.cfg和systemctl enable --now candy@candyB.cfg各一次吗？

**Comment by lanthora** [comment]
@ljty214 systemctl 的后面不跟 .cfg，仔细看我给的实示例

**Comment by ljty214** [comment]
ok
