### ISSUE TITLE
命令行运行窗口问题

### ISSUE THREAD

**Issue by ljty214** [lanthora/candy#424]
candy命令行运行窗口，一直在那挂着，有点碍事，不知道有没有办法关掉这个窗口，又不影响candy的运行？

**Comment by lanthora** [comment]
@ljty214 什么环境，windows gui 不需要命令行启动，Linux 有对应的服文件，docker 自己也能管理服务

**Comment by ljty214** [comment]
没办法，我有台win7系统，只能用candy命令行运行

**Comment by lanthora** [comment]
@ljty214 低版本 windows 可以用 nssm 或者 winsw 做成服务

**Comment by ljty214** [comment]
能否简略说下思路

**Comment by lanthora** [comment]
@ljty214 不能，你先去查 nssm 或者 winsw。如果搞不定就去他们的项目底下提问

**Comment by ljty214** [comment]
。。。。。。。。
