### ISSUE TITLE
网络网关问题

### ISSUE THREAD

**Issue by ljty214** [lanthora/candy#425]
默认网络demo，有网关吗？

**Comment by lanthora** [comment]
@ljty214 可以有，你遇到了什么具体的问题

**Comment by ljty214** [comment]
没遇到什么问题，好奇而已，一般网关都是管理内网的各客户端，而candy是通过canets.org网站管理的

**Comment by lanthora** [comment]
@ljty214 你对网关的理解是错误的。你说的那个东西不是网关，而只是刚好在默认网关上的管理界面

**Comment by ljty214** [comment]
那麻烦你说下网关是什么意思呢

**Comment by lanthora** [comment]
@ljty214 百度
