### ISSUE TITLE
虚拟机网络连接

### ISSUE THREAD

**Issue by DavidLdf** [lanthora/candy#426]
在Windows11启用镜像网络，开启wsl2的ubuntu22，桌面应用程序无法借用ubuntu系统内的candy网络来ping通另一台搭载candy的机器ip，所有candy都是启用默认设置，demo网络。请问该如何设置才能使这台Windows11的桌面程序可以访问candy网络？ubuntu系统candy网络可以正常使用。

**Comment by lanthora** [comment]
@DavidLdf 不了解 wsl2 的工作原理,如果没有办法在 win11 上看到新增的网卡和路由,这个方案大概率不行.

为什么不直接在 win11 上装客户端？

**Comment by DavidLdf** [comment]
创建一个沙盒环境，平时有些工作又需要用Windows来完成，得一起用两套系统，同时控制一些网络访问，我尝试一下桥接方案看看吧。谢谢解答

**Comment by lanthora** [comment]
@DavidLdf 在宿主机上再开一个客户端呢?

**Comment by DavidLdf** [comment]
为了某些程序的网络隔离
