### ISSUE TITLE
Default MTU 1400 Causing Packet Loss, Resolved by Lowering to 1280

### ISSUE THREAD

**Issue by flarecentury** [lanthora/candy#428]
## Problem Description

The service experienced packet loss when using the default MTU setting of 1400. The issue was resolved by lowering the MTU to 1280. The specific operation was:

```
ip link set MTU 1280 candy-xxx
```

After executing the above command on all machines, the service returned to normal operation.

## Suggested Investigation Directions

1. will candy allowed user to define the MTU value?

## 问题描述

服务在使用默认MTU设置1400时出现丢包现象。通过将MTU降低到1280，问题得到了解决。具体操作如下：

```
ip link set MTU 1280 candy-xxx
```

在所有机器执行上述命令后，服务恢复正常运行。

## 建议调查方向

1. candy是否允许用户自定义MTU值？

**Comment by lanthora** [comment]
@flarecentury 目前没有提供修改 MTU 的配置，在这里设置的 MTU：https://github.com/lanthora/candy/blob/master/src/core/client.cc#L781

可以添加命令行参数和配置文件参数，如果你能发 PR 就更好了

**Comment by flarecentury** [comment]
感谢！
