### ISSUE TITLE
candy有没有类似wireguard的Table = off 功能

### ISSUE THREAD

**Issue by shen09gsd** [lanthora/candy#442]
想通过类似wireguard的Table = off 功能用bird去管理路由表，现有的candy功能中有类似的设置选项吗

**Comment by lanthora** [comment]
@shen09gsd 用一个配置，禁止 candy 去修改系统路由表。手动或者用其他第三方工具修改路由表。

我这样理解对吗

**Comment by shen09gsd** [comment]
是的，差不多这个意思，wireguard的Table = off功能其实就是关闭修改系统路由表通过设置AllowedIPs = 0.0.0.0/0可以用bird导入路由表到系统路由，这样的用法在某些场景对于路由表的管理很方便

**Comment by lanthora** [comment]
@shen09gsd 能否说一下你的具体场景。

candy 目前的实现会严格过滤虚拟网卡收到的包，不是功能中明确要收到的包都不会处理，所有功能相关的路由表都自动配置了。

所以，不自动配置路由表，唯一我能想到的好处就是锻炼自己在不同系统下设置路由表的能力。而坏处却很多，少了该配置的路由表功能会不正常，多了不该配置的路由表也不会有任何功能上的收益

**Comment by shen09gsd** [comment]
比如公司有好几个分公司，每个公司宽带用的不同，有些服务在某些运营商的带宽上更稳定，老板想让让一个服务的ip段从网上的ip源列表种获取全部走另一个公司的网络去访问，那个服务的ip段列表中有大量的ip地址段 ，其实通过自动配置也能实现，只是自动配置有ip数量上限吗？bird的话可以用脚本自动获取互联网的ip段自动动态导入wireguard，如果要通过candy实现，要在服务端写大量的ip规则，或者换一种思路，是否candy可以从配置文件外部导入ip段列表？不过这个问题又要建立在candy能支持大量ip导入的情况下

**Comment by lanthora** [comment]
@shen09gsd 从设计上是支持同时在服务端导入大量路由的，实现上只能导入几百个，如果导入路由能解决你这个问题，可以修改实现解决这个问题。预估单机最多导入多少条？

需要先配置几条路由测试一下你的想法能不能实现，可以的话就能增加路由条数了。

**Comment by shen09gsd** [comment]
2000条左右可以满足我现在的需求，我试过几条路由通过candy服务端下发到客户端，可以满足我的需求，只是能导入的路由数量太少了，超出几百条现在会导致客户端没反应。另外我看到了文档中写了 这是反审查的组网工具 那我想到了另一个场景需求，比如在vps上把中国的ip段全部通过另一台服务器上网，这样可能需要导入的ip远远超过2000条

**Comment by lanthora** [comment]
@shen09gsd 我做这个只是为了组网的时候不被防火墙干扰。你现在这个需求更像是代理了，为什么不直接使用专门的工具，比如 dae。在使用 dae 的情况下，如果代理服务器在公司内网，就可以用 candy 来创建隧道了。

**Comment by shen09gsd** [comment]
dae看了下，厉害的项目，谢谢，我先去研究dae了

**Comment by lanthora** [comment]
> 超出几百条现在会导致客户端没反应

把这个当作问题处理了,以前的场景大部分用户配置的路由都非常有限. https://github.com/lanthora/candy/pull/443

> dae看了下，厉害的项目，谢谢，我先去研究dae了

我觉得这个能更好的解决你的的问题,如果不行的话,并且你用的是 cacao 作为服务端,可以去那个项目里开批量导入路由配置的 issue。这个我先关掉了
