### ISSUE TITLE
服务端路由规则怎么写？

### ISSUE THREAD

**Issue by jimmycart888** [lanthora/candy#446]
假设有5个局域网，具体信息如下：
ip为192.168.1.2，虚拟ip为10.10.10.1
ip为192.168.2.2，虚拟ip为10.10.10.2
ip为192.168.3.2，虚拟ip为10.10.10.3
ip为192.168.4.2，虚拟ip为10.10.10.4
ip为192.168.5.2，虚拟ip为10.10.10.5
上面的5个局域网需要互通，服务端的路由需要怎么写啊

**Comment by lanthora** [comment]
@jimmycart888 你只给出了局域网地址，没有给出子网，我这里假设子网掩码是 255.255.255.0，也就是 192.168.1.2/24。

因为所有局域网子网都不冲突，对于发往第一个局域网的配置就是: 给所有客户端下发配置，对于到达 192.168.1.0/24 的数据包，通过 10.10.10.1 转发。

对应的配置可以是: sdwan="10.10.10.0/24,192.168.1.2/24,10.10.10.1"

这样一行配置会下发给所有客户端，用同样的道理添加更多个配置就可以了，注意配置之间用;隔开

**Comment by jimmycart888** [comment]
我用的是wss://canets.org服务端，你说的sdwan="10.10.10.0/24,192.168.1.0/24,10.10.10.1"在哪里配呢？
我的理解是
![image](https://github.com/user-attachments/assets/0c400a3a-81df-4426-ab64-e7ac716d0f37)
![image](https://github.com/user-attachments/assets/26fed13d-0d5b-403a-897d-4c672601b0ac)
在这里配路由规则
不知道你说的sdwan="10.10.10.0/24,192.168.1.0/24,10.10.10.1"在哪里配呢？

**Comment by lanthora** [comment]
@jimmycart888 上面给出的是命令行版本的配置。canets.org 用的是 cacao 项目作为服务端的。

这个对应的配置从上往下分别是

1. 网络名，这个只能选
2. 10.10.10.0
3. 255.255.255.0
4. 192.168.1.0
5. 255.255.255.0
6. 10.10.10.1
7. 优先级，你这个需求里都可以写 0

按照同样的方式，添加多条配置，每天配置只需要改 4 和 6

**Comment by lanthora** [comment]
@jimmycart888 肉眼看不出来问题，检查输入的参数里有没有多余的空格。

另外，提问的时候最好带真实环境的 IP，不要自己编，增加沟通成本
