### ISSUE TITLE
ubuntu22.04，安装candy出错

### ISSUE THREAD

**Issue by jimmycart888** [lanthora/candy#447]
root@ubuntu-mini:~# sudo apt install --fix-broken candy_5.10.4+ubuntu22.04_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package candy_5.10.4+ubuntu22.04_amd64.deb

上面是错误信息，即使在执行apt update与apt upgrade后，仍然出现上面的错误。

**Comment by YangMame** [comment]
@jimmycart888 wiki是不是换成用sudo dpkg -i /path/to/candy.deb更好

**Comment by peeweep** [comment]
@jimmycart888 的错误在于没有在 candy_5.10.4+ubuntu22.04_amd64.deb 前边加 ./

**Comment by jimmycart888** [comment]
搞定
