### ISSUE TITLE
poco 1.14.0 compilation failed

### ISSUE THREAD

**Issue by zhongjixiuxing** [lanthora/candy#457]
苹果 Mabook Pro M1 chip 下使用` brew install candy` 过程中出现依赖问题导致安装失败

![fb16fb3356f3f2ba0685a3279e2802d8](https://github.com/user-attachments/assets/06bc8430-9328-4847-ac79-9a5f267f5d34)

**Comment by lanthora** [comment]
https://github.com/pocoproject/poco/issues/4798

**Comment by lanthora** [comment]
静态链接老版本 poco，临时解决这个问题，等上游发布修复这个问题后可以再恢复成以前的方式

@zhongjixiuxing 帮忙测试一下，如果没问题你就关掉这个 issue 吧
