### ISSUE TITLE
能不能支持备份服务器

### ISSUE THREAD

**Issue by oscnet** [lanthora/candy#461]
客户端能不能配置多个服务器，防止服务器掉线，全网就挂了。
这样当第一个服务器挂了后，客户端都能转到第二个服务器，重建网络。
以防止单点故障。

**Comment by lanthora** [comment]
@oscnet 目前没有这方面的设计，短期内也不考虑。

让服务端足够稳定的运行在目前测试环境上看不是一件困难的事情
